builds:
  - id: listener
    main: ./cmd/listener
    binary: listener/bootstrap
    flags:
      - -tags=lambda.norpc
      - -v
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    hooks:
      pre:
        - go mod tidy
    no_unique_dist_dir: true

archives:
  - id: listener
    builds:
      - listener
    format: zip
    wrap_in_directory: false
    strip_parent_binary_folder: true
    name_template: listener-lambda
